version: 0.1
env:
  parameter-store:
    SNYK_TOKEN: "snyk_key"
phases:
  pre_build:
    commands:
      - echo installing snyk
      - PWD=$(pwd)
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk

  build:
    commands:
      - echo commencing vulnerability scanning
      - ./snyk test --severity-threshold=medium
      - ./snyk monitor
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
