version: 0.1
env:
  parameter-store:
    SNYK_AUTH_TOKEN: "snyk_key"
phases:
  pre_build:
    commands:
      - echo installing snyk
      - SNYK_TOKEN=$SNYK_AUTH_TOKEN
      - PWD=$(pwd)
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      - echo $SNYK_TOKEN
      - echo $SNYK_AUTH_TOKEN
  build:
    commands:
      - echo commencing vulnerability scanning
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
