version: 0.1
env:
  parameter-store:
    SONAR_TOKEN: "sonar_test_token"
    SONAR_KEY: "sonar_test_key"
    variables:
      PROJECT_NAME: "gw-test-hello-world"
      ORGANIZATION_NAME: "gwillits"
phases:
install:
  runtime-versions:
    java: openjdk11
  pre_build:
  commands:
    - echo installing snyk
    - apt-get update
    - apt-get install -y jq
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -O sonar-scanner.zip
    - unzip ./sonar-scanner.zip
    - export PATH=$PATH:/sonar-scanner/bin/
    - echo $PATH

  build:
    commands:
      - echo commencing vulnerability scanning

      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
