[tool.poetry]
name = "hello-world-python"
version = "0.1.0"
description = ""
authors = ["Garry Willits <garry.willits@mail.com>"]

[tool.poetry.dependencies]
python = ">=3.5"
flask  = "*"
safety = "^1.10.3"
