[tool.poetry]
name = "_layer_boto"
version = "0.1.0"
description = ""
authors = ["NHS Digital"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.20.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
